//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAss
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public string Username { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Dob { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string ProfileImage { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
