//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAss
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumReply
    {
        public int ForumReplyId { get; set; }
        public string Username { get; set; }
        public string ForumReplyText { get; set; }
        public string ForumReplyDate { get; set; }
        public string ForumReplyTime { get; set; }
        public int ForumID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Forum Forum { get; set; }
    }
}
